- name: "Remove ntpd"
  apt: name=ntp state=absent purge=yes

- name: "Install openntpd"
  apt: name=openntpd state=latest

- name: "Create /etc/default/openntpd"
  copy:
    content: 'DAEMON_OPTS="-s -f /etc/openntpd/ntpd.conf"'
    dest: /etc/default/openntpd
    owner: root
    group: root
    mode: 0644
  notify: restart openntpd

- name: "Create openntpd/ntpd.conf"
  template: src=ntpd.conf.j2 dest=/etc/openntpd/ntpd.conf mode=644 owner=root group=root
  notify: restart openntpd
