- name: "Install nginx"
  apt: pkg=nginx state=latest

- name: "Install nginx conf file"
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: "Start nginx"
  service: name=nginx state=stopped

- name: "Remove apache"
  apt: name={{item}} state=absent purge=yes
  with_items:
    - apache2-mpm-worker
    - apache2
    - apache2.2-bin
    - apache2.2-common
