- name: "delete RIPE TAL"
  file:
    state: absent
    path: /etc/tals/ripe.tal

- name: "delete old pin file"
  file:
    state: absent
    path: /etc/apt/preferences.d/pin-rpki

- name: "TAL selection (rpki-trust-anchors)"
  debconf:
    name: rpki-trust-anchors
    question: rpki-trust-anchors/get_arin_tal
    vtype: boolean
    value: False
  changed_when: false

- name: "Install RPKI Trust Anchors"
  apt: pkg=rpki-trust-anchors state=latest

- name: "Only output JSON"
  copy: dest=/etc/default/rpki-client content="OPTIONS=-j"

- name: "Install rpki-client"
  apt: pkg=rpki-client state=latest

# The Ubuntu Bookworm package has .service file with more
# options than Bionic's systemd supports
- name: "Install bionic compatible systemd service file"
  copy:
    src: files/rpki-client.service
    dest: /lib/systemd/system/rpki-client.service
  notify: reload systemd
  when: ansible_distribution_release == 'bionic'
