- name: "APT pin the RPKI software to Bookworm"
  copy:
    src: files/pin-rpki
    dest: /etc/apt/preferences.d/pin-rpki
  when: ansible_distribution_release == 'bionic'

- name: "Run apt-get update"
  apt:
    update_cache: yes
  changed_when: false

- name: "TAL selection (rpki-trust-anchors)"
  debconf:
    name: rpki-trust-anchors
    question: rpki-trust-anchors/get_arin_tal
    vtype: boolean
    value: False
  changed_when: false

- name: "Install RPKI Trust Anchors"
  apt: pkg=rpki-trust-anchors state=latest

- name: "Only output JSON"
  copy: dest=/etc/default/rpki-client content="OPTIONS=-j"

- name: "Install rpki-client"
  apt: pkg=rpki-client state=latest

# The Ubuntu Bookworm package has .service file with more
# options than Bionic's systemd supports
- name: "Install bionic compatible systemd service file"
  copy:
    src: files/rpki-client.service
    dest: /lib/systemd/system/rpki-client.service
  notify: reload systemd
  when: ansible_distribution_release == 'bionic'
