- name: "Install various software packages"
  apt: name={{ item }} state=latest
  with_items:
    - apache2-utils
    - bash-completion
    - bc
    - bind9-host
    - bison
    - build-essential
    - bzr
    - command-not-found
    - curl
    - cvs
    - dbndns
    - dnsutils
    - dsniff
    - flex
    - fpdns
    - fping
    - git-core
    - gnupg
    - gnutls-bin
    - graphviz
    - hping3
    - htop
    - httping
    - iotop
    - ipcalc
    - iperf
    - iputils-ping
    - iputils-tracepath
    - jq
    - landscape-common
    - language-pack-en-base
    - ldnsutils
    - lft
    - lftp
    - libcache-cache-perl
    - libsqlite3-dev
    - libxml2-dev
    - lsof
    - ltrace
    - lynx
    - man-db
    - markdown
    - members
    - mercurial
    - moreutils
    - mtr-tiny
    - ndisc6
    - netcat-openbsd
    - netsed
    - ngrep
    - nmap
    - pastebinit
    - psmisc
    - pv
    - python
    - python-beautifulsoup
    - python-demjson
    - python-dnspython
    - python-flask
    - python-ipaddr
    - python-libxml2
    - python-mysqldb
    - python-networkx
    - python-pip
    - python-pycountry
    - python-setuptools
    - python-simplejson
    - python-software-properties
    - python-virtualenv
    - rsync
    - ruby
    - screen
    - sipcalc
    - snmp
    - socat
    - sshfp
    - strace
    - sysstat
    - tcpdump
    - tcptraceroute
    - telnet
    - tmux
    - traceroute
    - tshark
    - ucspi-tcp
    - unattended-upgrades
    - update-manager-core
    - update-notifier-common
    - vim
    - virt-what
    - w3m
    - wget
    - whois
    - swaks
    - ruby-json
    - libldns-dev

- name: "Install various software packages (precise)"
  apt: name={{ item }} state=latest
  with_items:
    - ruby1.9.3
    - ruby1.9.1-dev
    - libnet-ssh2-ruby1.8
    - php5-cli
  when: ansible_distribution_release == "precise"

- name: "Install various software packages (xenial)"
  apt: name={{ item }} state=latest
  with_items:
    - jsonlint
    - php7.0-cli
    - iperf3
    - ruby-dev
    - parallel
  when: ansible_distribution_release != "precise"

- name: "Create symlink for lft"
  file: src=/usr/sbin/lft dest=/usr/bin/lft state=link

- name: "Apply setuid root to some tools"
  file: path={{ item }} mode=4755
  with_items:
    - /bin/ping
    - /bin/ping6
    - /usr/sbin/lft

- name: "Allow ring-users to do wire capturing"
  file: path={{ item }} mode=0754 owner=root group=ring-users
  with_items:
    - /usr/sbin/tcpdump
    - /usr/bin/dumpcap

- name: "Get network capabilities for some tools"
  command: /sbin/getcap {{ item }}
  register: cap
  with_items:
    - /usr/sbin/hping3
    - /usr/bin/nmap
    - /usr/bin/nping
    - /usr/bin/traceroute.db
    - /usr/sbin/tcpdump
    - /usr/bin/dumpcap
  always_run: yes
  changed_when: false

- name: "Set new capabilities"
  command: /sbin/setcap cap_net_raw,cap_net_admin=eip {{ item.item }}
  when: item.stdout != "{{ item.item }} = cap_net_admin,cap_net_raw+eip"
  with_items: "{{ cap.results }}"

- name: "Uninstall certain unnecessary packages"
  apt: name={{ item }} state=absent
  with_items:
    - ferm
    - molly-guard
    - mtr
    - pppoe
    - ppp
    - pppconfig
    - pppoeconfig
    - resolvconf
    - sl
    - ufw

- name: "Uninstall certain unnecessary packages - except on pdnsmaster"
  apt: name={{ item }} state=absent
  with_items:
    - apparmor
    - apparmor-utils
  when: pdnsmaster|default(None) != true
