- hosts: all
  become: true
  become_user: root
  roles:
    - ansible
    - etcfiles
    - fail2ban
    - { role: users, class: ring-admins }
    - { role: users, class: local }

- hosts: ringnode:auth.infra.ring.nlnog.net
  become: true
  become_user: root
  roles:
    - { role: users, class: ring-users }

- hosts: lg01.infra.ring.nlnog.net
  become: true
  become_user: root
  roles:
    - { role: users, class: ring-users, user_shell: /usr/local/bin/birdshell }

- hosts: public02.infra.ring.nlnog.net
  become: true
  become_user: root
  roles:
    - { role: haproxy, profile: github }

