- hosts: ringnode
  tasks:
    - include_vars: "vault/ringnode.yml"
  tags:
    - always

#- hosts: infranode
#  tasks:
#    - include_vars: "vault/infranode.yml"
#  tags:
#    - always

- include: ubuntu_upgrade.yml
  when: '"ringnode" in group_names and ansible_distribution_release != "xenial"'

- hosts: all
  become: true
  become_user: root
  roles:
    - { role: resolving, tags: resolving }
    - { role: etcfiles, tags: etcfiles }
    - { role: syslog, tags: syslog }
    - { role: sysctl, tags: sysctl }
    - { role: lang, tags: lang }
    - { role: apt, tags: apt }
    - { role: ansible, tags: ansible }
    - { role: software, tags: software }
    - { role: ntp, tags: ntp }
    - { role: motd, tags: motd }
    - { role: munin-node, tags: munin-node }
    - { role: dhcp, tags: dhcp }
    - { role: fail2ban, tags: fail2ban }
    - { role: postfix, tags: postfix }
    - { role: userscripts, tags: userscripts }
    - { role: adminscripts, tags: adminscripts }
    - { role: users, class: ring-admins, tags: ring-admins }
    - { role: users, class: local, tags: local-users }
    - { role: openssh, tags: openssh }

- hosts: ringnode:auth.infra.ring.nlnog.net
  become: true
  become_user: root
  roles:
    - { role: users, class: ring-users, tags: ring-users }

- hosts: ringnode
  become: true
  become_user: root
  roles:
    - { role: nginx, tags: nginx }
    - { role: scamper, tags: scamper }
    - { role: ripe-atlas, tags: ripe-atlas }
    - { role: ring_sqa, tags: ring_sqa }
    - { role: ringfpingd, tags: ringfpingd }
    - { role: upgrade, tags: upgrade, when: ansible_distribution_release == 'precise'}

- hosts: infranode
  become: true
  become_user: root
  roles:
    - { role: backup-client, tags: backup-client }

- hosts: master01.infra.ring.nlnog.net:public02.infra.ring.nlnog.net:public03.infra.ring.nlnog.net:compute02.infra.ring.nlnog.net
  become: true
  become_user: root
  roles:
    - { role: apache2, tags: apache2 }

- hosts: compute01.infra.ring.nlnog.net
  become: true
  become_user: root
  roles:
    - { role: munin-master, tags: munin-master }

- hosts: lg01.infra.ring.nlnog.net
  become: true
  become_user: root
  roles:
    - { role: bird, tags: bird }
    - { role: bird-lg, tags: bird-lg }
    - { role: users, class: ring-users, user_shell: /usr/local/bin/birdshell, tags: ring-users }

- hosts: public02.infra.ring.nlnog.net
  become: true
  become_user: root
  roles:
    - { role: haproxy, profile: github, tags: haproxy }
    - { role: inframail, tags: inframail }

- hosts: backup.infra.ring.nlnog.net:storage01.infra.ring.nlnog.net
  become: true
  become_user: root
  roles:
    - { role: backup-server, tags: backup-server }

- hosts: auth.infra.ring.nlnog.net
  become: true
  become_user: root
  roles:
    - { role: ring_auth, tags: ring_auth }

