- hosts: all
  become: true
  become_user: root
  roles:
    - ansible
    - etcfiles
    - fail2ban
    - software
    - { role: ntp, tags: ntp }
    - { role: users, class: ring-admins }
    - { role: users, class: local }

- hosts: ringnode:auth.infra.ring.nlnog.net
  become: true
  become_user: root
  roles:
    - { role: users, class: ring-users }

- hosts: ringnode
  become: true
  become_user: root
  roles:
    - { role: nginx, tags: nginx }
    - { role: scamper, tags: scamper }
    - { role: ripe-atlas, tags: ripe-atlas }
    - { role: ring_sqa, tags: ring_sqa }


- hosts: lg01.infra.ring.nlnog.net
  become: true
  become_user: root
  roles:
    - { role: users, class: ring-users, user_shell: /usr/local/bin/birdshell }

- hosts: public02.infra.ring.nlnog.net
  become: true
  become_user: root
  roles:
    - { role: haproxy, profile: github }

