- hosts: all
  gather_facts: false
  become: true
  become_user: root
  pre_tasks:
    - name: Install python
      raw: sudo apt-get install -y python

- hosts: all
  tasks:
    - name: Check if /etc/ansible/ring exists
      stat:
        path: /etc/ansible/ring
      register: etc_ansible_ring
    - name: Ensure an existing host is not provisioned
      fail:
        msg: This host is already provisioned!
      when: etc_ansible_ring.stat.exists

- hosts: all
  tasks:
    - name: Check IPv4 connectivity
      command: ping -c 4 ring.nlnog.net
      register: check_v4
    - fail:
        msg: Could not ping ring.nlnog.net (IPv4)
      when: check_v4.rc != 0
    - name: Check IPv6 connectivity
      command: ping -c 4 ring.nlnog.net
      register: check_v6
    - fail:
        msg: Could not ping ring.nlnog.net (IPv6)
      when: check_v6.rc != 0
    - name: Check CPU architecture
      shell: lscpu | grep -qe 'Architecture:\s*x86_64'
      register: check_arch
    - fail:
        msg: Host is not an x86_64 system
      when: check_arch.rc != 0

- hosts: ringnode
  become: true
  become_user: root
  tasks:
    - name: Load the vault passwords
      include_vars: "vault/vault.yml"
    - name: Add the vault password
      copy:
        dest: /root/.vaultpw
        mode: 0400
        content: "{{ ringnode_vault_pw }}"

- hosts: infranode
  become: true
  become_user: root
  tasks:
    - name: Load the vault passwords
      include_vars: "vault/vault.yml"
    - name: Add the vault password
      copy:
        dest: /root/.vaultpw
        mode: 0400
        content: "{{ infranode_vault_pw }}"

- hosts: all
  become: true
  become_user: root
  roles:
    - { role: etcfiles, tags: etcfiles }
    - { role: apt, tags: apt }
    - { role: ansible, tags: ansible }
    - { role: users, class: ring-admins, tags: ring-admins }
  tasks:
    - name: Upgrade all packages
      apt:
        upgrade: dist
    - name: Reboot
      command: /sbin/reboot
