- hosts: all
  become: true
  become_user: root
  roles:
    - { role: apt, tags: apt }
    - { role: ansible, tags: ansible, mitogen_update: yes }
  tasks:
    - name: "Configure temporary dpkg options" 
      copy:
        dest: /etc/apt/apt.conf.d/local
        mode: 0644
        content: 'DPkg::options { "--force-confold"; }'

    - name: "Disable ansible cron"
      file:
        name=/etc/cron.d/ansible
        state=absent
      when: ansible_distribution_release != "xenial"
  tags:
    - prepare

- hosts: all
  become: true
  become_user: root
  tasks:
    - name: "Make sure unupgradable packages are gone"
      apt: name={{ item }} state=absent
      with_items:
        - puppet-common
        - puppet
        - libsodium13
        - keyboard-configuration
        - daemontools-run
        - console-setup-linux
        - console-setup
        - kbd

    - name: "Remove automatic update files"
      file: name={{ item }} state=absent
      with_items:
        - /etc/apt/apt.conf.d/50unattended-upgrades
        - /etc/apt/apt.conf.d/50unattended-upgrades.dpkg-dist

    - name: "Add ubuntu trusty repository"
      apt_repository:
        repo: 'deb http://ftp.bit.nl/ubuntu trusty main restricted universe multiverse'
        state: present
        filename: 'ubuntu_archiv_trusty'
      when: ansible_distribution_release == "precise"

    - name: "Add ubuntu trusty updates repository"
      apt_repository:
        repo: 'deb http://ftp.bit.nl/ubuntu trusty-updates main restricted universe multiverse'
        state: present
        filename: 'ubuntu_archiv_trusty-updates'
      when: ansible_distribution_release == "precise"

    - name: "Add ubuntu trusty security repository"
      apt_repository:
        repo: 'deb http://ftp.bit.nl/ubuntu trusty-security main restricted universe multiverse'
        state: present
        filename: 'ubuntu_archiv_trusty-security'
      when: ansible_distribution_release == "precise"

    - name: "Remove ubuntu precise repositories"
      file: name={{ item }} state=absent
      with_items:
        - '/etc/apt/sources.list.d/ubuntu_archiv_precise-security.list'
        - '/etc/apt/sources.list.d/ubuntu_archiv_precise-updates.list'
        - '/etc/apt/sources.list.d/ubuntu_archiv_precise.list'

    - name: "apt-get update (trusty repos)"
      apt:
        update_cache: yes
      when: ansible_distribution_release == "precise"

    - name: "Perform release upgrade (precise -> trusty)"
      command: do-release-upgrade -f DistUpgradeViewNonInteractive
      when: ansible_distribution_release == "precise"
  tags:
    - trusty

- hosts: all
  become: true
  become_user: root
  tasks:
    - name: "Remove daemontools-run"
      apt: name={{ item }} state=absent
      with_items:
        - daemontools-run
    
    - name: "Remove automatic update files"
      file: name={{ item }} state=absent
      with_items:
        - /etc/apt/apt.conf.d/50unattended-upgrades
        - /etc/apt/apt.conf.d/50unattended-upgrades.dpkg-dist

    - name: "Add ubuntu xenial repository"
      apt_repository:
        repo: 'deb mirror://mirrors.ubuntu.com/mirrors.txt xenial main restricted universe multiverse'
        state: present
        filename: 'ubuntu_archiv_xenial'

    - name: "Add ubuntu xenial updates repository"
      apt_repository:
        repo: 'deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-updates main restricted universe multiverse'
        state: present
        filename: 'ubuntu_archiv_xenial-updates'

    - name: "Add ubuntu xenial security repository"
      apt_repository:
        repo: 'deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-security main restricted universe multiverse'
        state: present
        filename: 'ubuntu_archiv_xenial-security'

    - name: "Remove ubuntu trusty repositories"
      file: name={{ item }} state=absent
      with_items:
        - '/etc/apt/sources.list.d/ubuntu_archiv_trusty.list'
        - '/etc/apt/sources.list.d/ubuntu_archiv_trusty-updates.list'
        - '/etc/apt/sources.list.d/ubuntu_archiv_trusty-security.list'

    - name: "apt-get update (xenial repos)"
      apt:
        update_cache: yes

    - name: "Perform release upgrade (trusty -> xenial)"
      command: do-release-upgrade -f DistUpgradeViewNonInteractive
      when: ansible_distribution_release != "xenial"
  tags:
    - xenial

- hosts: all
  become: true
  become_user: root
  tasks:
    - name: "Remove automatic update files"
      file: name={{ item }} state=absent
      with_items:
        - /etc/apt/apt.conf.d/50unattended-upgrades
        - /etc/apt/apt.conf.d/50unattended-upgrades.dpkg-dist

    - name: "Add ubuntu bionic repository"
      apt_repository:
        repo: 'deb mirror://mirrors.ubuntu.com/mirrors.txt bionic main restricted universe multiverse'
        state: present
        filename: 'ubuntu_archiv_bionic'

    - name: "Add ubuntu bionic updates repository"
      apt_repository:
        repo: 'deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-updates main restricted universe multiverse'
        state: present
        filename: 'ubuntu_archiv_bionic-updates'

    - name: "Add ubuntu bionic security repository"
      apt_repository:
        repo: 'deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-security main restricted universe multiverse'
        state: present
        filename: 'ubuntu_archiv_bionic-security'

    - name: "Remove ubuntu xenial repositories"
      file: name={{ item }} state=absent
      with_items:
        - '/etc/apt/sources.list.d/ubuntu_archiv_xenial.list'
        - '/etc/apt/sources.list.d/ubuntu_archiv_xenial-updates.list'
        - '/etc/apt/sources.list.d/ubuntu_archiv_xenial-security.list'

    - name: "apt-get update (bionic repos)"
      apt:
        update_cache: yes

    - name: "Perform release upgrade (xenial -> bionic)"
      command: do-release-upgrade -d -f DistUpgradeViewNonInteractive
      when: ansible_distribution_release != "bionic"

    - name: "Remove daemontools"
      apt: name={{ item }} state=absent
      with_items:
        - daemontools
  tags:
    - bionic

- hosts: all
  become: true
  become_user: root
  roles:
    - { role: apt, tags: apt }
    - { role: ansible, tags: ansible }
  tasks:
    - name: "Remove temporary dpkg configuration" 
      file:
        name: /etc/apt/apt.conf.d/local
        state: absent

    - name: "Remove spurious automatic update file"
      file: name={{ item }} state=absent
      with_items:
        - /etc/apt/apt.conf.d/50unattended-upgrades.dpkg-dist

    - name: "Remove old virtual environments"
      file: name={{ item }} state=absent
      with_items:
        - /usr/share/ripe-atlas-venv
  tags:
    - cleanup

