- name: "Create /root/.ssh"
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700

- name: "Install rsync validation script"
  copy:
    src=validate-rsync-backup
    dest=/root/validate-rsync-backup
    owner=root
    group=root
    mode=0755

- name: "Add backup.infra rsa key"
  lineinfile:
    destfile: /root/.ssh/authorized_keys
    regexp: 'root@backup.infra.ring.nlnog.net'
    line: 'from="109.72.93.35,2a00:f10:122::35",command="/root/validate-rsync-backup" ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9zR9lQ7mr8aWhAzJBUhbTCg6RaMR0aSIpafvXjNiCzZg1yO+QOkw8N8i0lwyxND5xHiT4pgaL4ILqJ7SefocIU9MgcY77YUFHzkpOFjGpSF8I0nY4Q0WlYC0XFJvO4hx7sUXFBQze55Xbe4OBEEJoKCBbfCXEwgiPobXrcKSoCjT49hcz4F3q5MxEHgu1wvXzG7eiOyCtsNW5T/I5vImt0usP7SKGBBnWLZY92pfbtmqDwZ1q1joaM/qADO0E1YiXTL8QTtuhG5PMC8khAjZ9AzljaMi9UX1vjKWG7DL6VVSTv6nI1GNLABg8/Cwq69Dujho6zezWOANega6mEhzh root@backup.infra.ring.nlnog.net'

- name: "Add storage01.infra rsa key"
  lineinfile:
    destfile: /root/.ssh/authorized_keys
    regexp: 'root@storage01.infra.ring.nlnog.net'
    line: 'from="52.18.186.201,2a01:578:3::3412:bac9",command="/root/validate-rsync-backup" ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPbHCX7dsU6DlTxOCCh5+f+OxDTuuaIkrckgFX6/boqtkdeKzDIOmKfO+QNvngcJvwSQ0fcwd41ijq0xdy8LKeNP59nyOHyd7s4ZVK4whVWBGwh3D0zWvfXmhycaEwPV/9lGEyqSJ7+GNHkQmIxcZwg5BT/Y+AnWv5FDRnJNbxRm9Va7PMnq5/vSdCRc8LNZFkpiUz6w9KQPEMulBEuYVNo2PvbDWLhuZVpNKMEmE+5kRxK9/OOQ4SZnU3LKQEQsJfEtKjafeYvSDsQgq0ZOsgWVk1sXwTeaUWuCPQRzX2APxCubJLHduUC9GTanefTohcuYNYCn/98rZ+JUD0qjSp root@storage01.infra.ring.nlnog.net'

