- name: "Install prequisites for apt_repository"
  apt: name={{ item }} state=latest
  with_items:
    - python-apt
    - ca-certificates

- name: "Clean sources.list"
  copy:
    src=sources.list
    dest=/etc/apt/sources.list
    owner=root
    group=root
    mode=0644

- name: "Remove old repo files"
  file: name={{ item }} state=absent
  with_items:
    - 'ubuntu_archiv_precise.list'
    - 'ubuntu_archiv_precise-updates.list'
    - 'ubuntu_archiv_precise-security.list'
    - 'ubuntu_archiv_trusty.list'
    - 'ubuntu_archiv_trusty-updates.list'
    - 'ubuntu_archiv_trusty-security.list'
    - 'ubuntu_archiv_xenial.list'
    - 'ubuntu_archiv_xenial-updates.list'
    - 'ubuntu_archiv_xenial-security.list'

- name: "Add ubuntu {{ ansible_distribution_release }} repository"
  apt_repository:
    repo: 'deb http://ftp.bit.nl/ubuntu {{ ansible_distribution_release }} main restricted universe multiverse'
    state: present
    filename: 'bit_ubuntu_archiv_{{ ansible_distribution_release }}'

- name: "Add ubuntu {{ ansible_distribution_release }} updates repository"
  apt_repository:
    repo: 'deb http://ftp.bit.nl/ubuntu {{ ansible_distribution_release }}-updates main restricted universe multiverse'
    state: present
    filename: 'bit_ubuntu_archiv_{{ ansible_distribution_release }}-updates'

- name: "Add ubuntu {{ ansible_distribution_release }} security repository"
  apt_repository:
    repo: 'deb http://ftp.bit.nl/ubuntu {{ ansible_distribution_release }}-security main restricted universe multiverse'
    state: present
    filename: 'bit_ubuntu_archiv_{{ ansible_distribution_release }}-security'

- name: "Install nlnog repo key"
  apt_key:
    id: 37B0CA14
    url: "https://ring.nlnog.net/nlnogrepopublic.key"
    state: present

- name: "Add nlnog apt repository"
  apt_repository:
    repo: 'deb http://apt.ring.nlnog.net/deb/ maverick main'
    state: present
    filename: 'nlnog_ring_repo'

- name: "Install ansible repo key"
  apt_key:
    id: 7BB9C367
    url: "https://ring.nlnog.net/ansiblerepopublic.key"
    state: present
  when: ansible_distribution_release == "precise"

- name: "Remove ansible repo key"
  apt_key:
    id: 7BB9C367
    url: "https://ring.nlnog.net/ansiblerepopublic.key"
    state: absent
  when: ansible_distribution_release != "precise"

- name: "Add ansible repository"
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu precise main'
    state: present
    filename: 'ansible_repo'
  when: ansible_distribution_release == "precise"

- name: "Remove ansible repository"
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu precise main'
    state: absent
    filename: 'ansible_repo'
  when: ansible_distribution_release != "precise"

- name: "Add apt configuration files"
  copy:
    src={{ item }}
    dest=/etc/apt/apt.conf.d/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
