- name: "Install apache2 and friends"
  apt: name={{ item }} state=latest
  with_items:
    - apache2
    - libapache2-mod-wsgi

- name: "Remove apache2 placeholder site"
  file:
    path: /etc/apache2/sites-enabled/000-default
    state: absent

- name: "Enable apache2 headers module"
  file:
    src: /etc/apache2/mods-available/headers.load
    dest: /etc/apache2/mods-enabled/headers.load
    state: link
  notify: restart apache2

- name: "Enable apache2 ssl module (1)"
  file:
    src: /etc/apache2/mods-available/ssl.load
    dest: /etc/apache2/mods-enabled/ssl.load
    state: link
  notify: restart apache2

- name: "Enable apache2 ssl module (2)"
  file:
    src: /etc/apache2/mods-available/ssl.conf
    dest: /etc/apache2/mods-enabled/ssl.conf
    state: link
  notify: restart apache2

- name: "Install apache2 main config"
  copy:
    src="apache2.conf"
    dest="/etc/apache2/apache2.conf"
    owner=root
    group=root
    mode=0644
  notify: restart apache2

- name: "Install wsgi daemon config"
  copy:
    src="wsgi_daemons.conf"
    dest="/etc/apache2/wsgi_daemons.conf"
    owner=root
    group=root
    mode=0644
  notify: restart apache2

- name: "Create vhost directories"
  file:
    path: "/var/www/{{ item }}.ring.nlnog.net"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{ apache_vhosts|default([]) }}"

- name: "Install vhosts"
  copy:
    src="{{ item }}-vhost.conf"
    dest="/etc/apache2/sites-available/{{ item }}.ring.nlnog.net"
    owner=root
    group=root
    mode=0644
  with_items: "{{ apache_vhosts|default([]) }}"
  notify: restart apache2

- name: "Enable vhosts"
  file:
    src: "/etc/apache2/sites-available/{{ item }}.ring.nlnog.net"
    dest: "/etc/apache2/sites-enabled/{{ item }}.ring.nlnog.net.conf"
    owner: root
    group: root
    state: link
  with_items: "{{ apache_vhosts|default([]) }}"
  notify: restart apache2

- name: "Start apache2"
  service: name=apache2 state=started

