ntp_servers:
 - time.nist.gov
 - ntp.ring.nlnog.net
 - ntp2.ring.nlnog.net
 - ntp3.ring.nlnog.net
 - ntp1.tdc.fi
 - ntp3.tdc.fi
 - ntp0.nl.net
ntp_constraints:
 - nlnog.net
 - www.bit.nl
 - www.nist.gov
 - ietf.org
