
- name: install postfix packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ postfix_packages }}"

- name: create postfix config
  template:
    src: "{{ item }}"
    dest: /etc/postfix/
  notify:
    - reload systemd
    - postfix reload service
  with_items:
    - main.cf
    - master.cf
    - smtp_reply_filter

- name: stat /etc/postfix/postfix-files
  stat: path=/etc/postfix/postfix-files
  register: etc_postfix_postfix_files

- name: move /etc/postfix/postfix-files.dpkg-dist /etc/postfix/postfix-files
  command: mv /etc/postfix/postfix-files.dpkg-dist /etc/postfix/postfix-files
  when:
    - etc_postfix_postfix_files.exists == False
    - ansible_distribution_release == 'xenial'

- name: reload systemd if needed
  meta: flush_handlers

- name: enable postfix service
  service:
    name: postfix
    enabled: yes
    state: started

