
- name: Create scamper user
  user:
    name: scamper
    comment: Scamper measurements
    uid: 2001
    group: ring-users
    shell: /bin/bash

- name: Set up authorized_keys for the scamper user
  authorized_key:
    user: scamper
    key: "{{ item }}"
    state: present
  with_file:
    - ../keys/scamper.pub

- name: Install scamper packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - libscamperfile0
    - scamper

- name: Create /home/scamper/traces
  file:
    name: /home/scamper/traces
    state: directory
    owner: scamper

- name: scamper systemd service
  template:
    src: scamper.service.j2
    dest: /etc/systemd/system/scamper.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart scamper.service

- name: Delete old scamper files
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /etc/init/scamper.conf
    - /lib/systemd/system/scamper.conf
    - /lib/systemd/system/scamper.service

- name: Create /home/scamper/run-traces.sh
  copy:
    src: run-traces.sh
    dest: /home/scamper/run-traces.sh
    owner: scamper
    group: ring-users
    mode: 0755

- name: Create /etc/cron.d/scamper
  template:
    src: cron.d/scamper.j2
    dest: /etc/cron.d/scamper
    owner: root
    group: root
    mode: 0644

- name: clean up old cron entry comments
  lineinfile:
    dest: "{{ item }}"
    regexp: "(run_scamper|/home/scamper/run-traces|cleanup_scamper|find /home/scamper/traces)"
    state: absent
  with_items:
    - /var/spool/cron/crontabs/scamper
    - /var/spool/cron/crontabs/root

- name: scamper systemd service
  systemd:
    name: scamper
    state: started
    enabled: yes
    daemon_reload: yes
