- name: "Check for virtual env (temp)"
  stat:
    path: /usr/share/ripe-atlas-venv
  register: stat_atlas

- name: "Remove old virtual environment (temp)"
  file: name={{ item }} state=absent
  with_items:
    - /usr/share/ripe-atlas-venv
  when: ansible_distribution_release == "xenial" and stat_atlas.stat.exists == True

- name: "Install deb prequisites for ripe-atlas-tools"
  apt: name={{ item }} state=present
  with_items:
    - python-dev
    - libffi-dev
    - libssl-dev
    - python-virtualenv
    - python-pip

- name: "Install ripe-atlas-tools"
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ ripe_atlas_venv_dir }}"
    virtualenv_python: python2.7
  with_items:
    - IPy
    - pyOpenSSL
    - ndg-httpsclient
    - pyasn1
    - 'git+https://github.com/RIPE-NCC/ripe-atlas-tools@latest#egg=ripe-atlas-tools'

- name: "create symlinks for ripe-atlas-tools"
  file:
    state: link
    force: true
    src: "{{ ripe_atlas_venv_dir }}/bin/{{ item }}"
    path: "/usr/local/bin/{{ item }}"
  with_items:
    - adig
    - ahttp
    - antp
    - aping
    - asslcert
    - atraceroute
    - ndg_httpclient
    - ripe-atlas
    - wsdump.py
