- name: "Load peer list"
  include_vars: peers.yml

- name: "Add bird apt repo key"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 52463488670E69A092007C24F2331238F9C59A45 

- name: "Add bird apt repository"
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/cz.nic-labs/bird/ubuntu xenial main'
    state: present
    filename: 'cz_nic-labs-bird-precise.list'

- name: "Install bird and friends"
  apt: name={{ item }} state=latest
  with_items:
    - bird
    - dialog
    - nginx

- pip:
    name: rtrsub
    state: latest
    executable: pip3

- pip:
    name: requests
    state: latest

- name: "Install rtrsub rpki template"
  copy:
    src=bird-rtrsub-template.j2
    dest=/etc/bird/rpki.j2
    owner=root
    group=root
    mode=0444

- name: "Install table dump script"
  copy:
    src=fetchtables.sh
    dest=/usr/local/bin/fetchtables.sh
    owner=root
    group=root
    mode=0755

- name: "Dump tables every 5 minutes cronjob"
  cron:
    name: fetchtables
    job: /usr/local/bin/fetchtables.sh
    hour: '*'
    minute: '*/10'
    user: root

- name: "refresh ipv4 rtrsub configuration"
  command: "rtrsub --afi ipv4 -t /etc/bird/rpki.j2 -o /etc/bird/rpki-ipv4.conf"
  notify: reload bird

- name: "refresh ipv6 rtrsub configuration"
  command: "rtrsub --afi ipv6 -t /etc/bird/rpki.j2 -o /etc/bird/rpki-ipv6.conf"
  notify: reload bird6

- name: "Install bird.conf"
  template: src=bird.conf.j2 dest=/etc/bird/bird.conf
  notify: reload bird

- name: "Install bird6.conf"
  template: src=bird6.conf.j2 dest=/etc/bird/bird6.conf
  notify: reload bird6

- name: "Install birdshell"
  copy:
    src=birdshell
    dest=/usr/local/bin/birdshell
    owner=root
    group=root
    mode=0755

- name: "Add birdshell to shells"
  lineinfile:
    name: /etc/shells
    line: /usr/local/bin/birdshell

- name: "Start bird"
  service: name=bird state=started

- name: "Start bird6"
  service: name=bird6 state=started

- name: "Set bird sockets ownership"
  file:
    path: /var/run/bird/{{ item }}
    owner: bird
    group: ring-users
  with_items:
    - bird.ctl
    - bird6.ctl

