- name: "Load peer list"
  include_vars: peers.yml

- name: "Add bird apt repository"
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/cz.nic-labs/bird/ubuntu precise main'
    state: present
    filename: 'cz_nic-labs-bird-precise.list'

- name: "Install bird and friends"
  apt: name={{ item }} state=latest
  with_items:
    - bird
    - dialog

- pip:
    name: rtrsub
    state: latest

- pip:
    name: requests
    state: latest

- name: "Install rtrsub rpki template"
  copy:
    src=bird-rtrsub-template.j2
    dest=/etc/bird/rpki.j2
    owner=root
    group=root
    mode=0444

- name: "refresh ipv4 rtrsub configuration"
  command: "rtrsub --afi ipv4 -t /etc/bird/rpki.j2 -o /etc/bird/rpki-ipv4.conf"

- name: "refresh ipv6 rtrsub configuration"
  command: "rtrsub --afi ipv6 -t /etc/bird/rpki.j2 -o /etc/bird/rpki-ipv6.conf"

- name: "Install bird.conf"
  template: src=bird.conf.j2 dest=/etc/bird/bird.conf
  notify: reload bird

- name: "Install bird6.conf"
  template: src=bird6.conf.j2 dest=/etc/bird/bird6.conf
  notify: reload bird6

- name: "Install birdshell"
  copy:
    src=birdshell
    dest=/usr/local/bin/birdshell
    owner=root
    group=root
    mode=0755

- name: "Install rtrsub rpki template"
  copy:
    src=bird-rtrsub-template.j2
    dest=/etc/bird/rpki.j2
    owner=root
    group=root
    mode=0444

- name: "Add birdshell to shells"
  lineinfile:
    name: /etc/shells
    line: /usr/local/bin/birdshell

- name: "Start bird"
  service: name=bird state=started

- name: "Start bird6"
  service: name=bird6 state=started

