---
# local service user
- include: user.yml
  when: kafka_configure_broker or kafka_configure_zookeeper

# download + unpack kafka
- include: install.yml
  when: kafka_configure_broker or kafka_configure_zookeeper

# Kafka configs
- include: kafka.yml
  when: kafka_configure_broker

- include: zookeeper.yml
  when: kafka_configure_zookeeper
