- name: "Ensure output directory exists"
  file:
    path: /var/www/ring
    state: directory
    mode: 0755

- name: "Install the ring-health script"
  copy:
    src=ring-health
    dest=/usr/local/sbin/ring-health
    owner=root
    group=root
    mode=755

- name: "Ensure ring-health cronjob exists"
  template:
    src: cron.d/ring-health.j2
    dest: /etc/cron.d/ring-health

