- name: "Ensure the hostname is set in /etc/hostname"
  copy:
    dest: /etc/hostname
    content: "{{ ansible_nodename }}"

- name: "Ensure the hostname is set"
  hostname:
    name: "{{ ansible_nodename }}"

- name: "Generate /etc/hosts"
  template: src=hosts.j2 dest=/etc/hosts

- name: "Add upstart-job"
  copy:
    src=upstart-job
    dest=/lib/init/upstart-job
    owner=root
    group=root
    mode=0755

