- name: "Install mysql-server"
  apt: name=mysql-server state=latest

- name: "Install my.cnf"
  copy:
    src=my.cnf
    dest=/etc/mysql/my.cnf
    owner=root
    group=root
    mode=0644
  notify: reload mysql
