GROUPS:
  ring-admins:
    gid: 6000
    sudo: true
  ring-users:
    gid: 5000

USERS:
  job:
    state: present
    company: 'Job Snijders'
    email: job@instituut.net
    uid: 6001
    shell: /bin/bash
    groups:
      - ring-admins
      - ring-users
    sshkeys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA4Ejc9Q/RwP5rEY51RdKY3BHpXWYSmePBoppyEjJR5t+/rD7Q2pwbsbrgIm960TpqnOf8ExTje5fCj9yosvqFPgt6K2Tp/9WDkCxMfPj7Fc2rVCFxoTaa2tM/xCgYQpcp+adH/GI0lCsC07FFUHI4+81YLJsxxBm/QExB2gqVZCMH5j+s8q2iWMEQMyXtOdU02/EilUcAcUhPAgoT+U7OG/6bsrBBbVHegQs6uNHfuJtQMh/mmDAeo+qGqBsAIKMtc5H9VGaXNg7jd6wvn8+3EYQ+B1B7NKxEZt/xtWKK4fSdfWiyQY8ZJlGKHrI60dyrW2yKuqcyX3W2hUSQQzp9rQ== job@instituut.net-nlnogring-2011"

  martin:
    state: present
    company: 'Martin Pels'
    email: martin@rodecker.nl
    uid: 6002
    shell: /bin/bash
    groups:
      - ring-admins
      - ring-users
    sshkeys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArZl+3qDiBGF4v3fszgwFti5e4xVoY1fbXsqpAZmbZm1pbSlpJBsHc6ObrxepypoRik5JuiuAoLVFBziEq3m+GgMnUHYbdSBeqHJloa3bIdy8byVGowIYwV4zZyRCwEYuvto7xfUScCSgboBoHs+hU58kyYQxwWRZVCIhEMSIYlwHDCR3juHV1Z50XxgZEJgZeyKxGL4oeeLq9zbQDQxhglygia7nPXUVh+4Z2w6S7oS8prJH5saOg5ixtnBP3isQ5/WOwdAJrcu30s+4P6eWvcJQVtRNZDJyNCctkjCPaN2PVNRvhEu6oeWptwb/pek6LSwmKvUETUHz4W4FKHCKPw== martin@rodecker.nl"

  edwin:
    state: absent

  peter:
    state: present
    company: "Peter van Dijk"
    email: peter+ring@7bits.nl
    uid: 6004
    shell: /bin/bash
    groups:
      - ring-admins
      - ring-users
    sshkeys:
      - "ssh-dss AAAAB3NzaC1kc3MAAAEBANPt8mExz5YFc/D/c3hGYdPJr6u+qUPDYqA7LQC9p7jLotLq+PmwJsjKJZQ6kd78DrQi9Cx4A9YwjCyZAxZN43NbzNImMhfr1/ZKv+Akx2cybolgmN4AKDf3rvBpQL+56zO1j4tYsc1h0b2Zpllq/Gk4/llqiiQeL2ldMEmc5n1uotGrbjsCBRIJJSGeHJsYcWeZcx8n/m4GHh1dYEmIujh+F6BdVLIDz/1F3GBdNmyU5jgNuEFW7TeYeEcgWbWzGWWkM8P5pUAKUr8Kg9BA4pLdgWpcU++Oz0cA8OUvS+XBZ7kfvwK4hX8RiB08O3Wa6XAC40x0rS9YkVHih1o9JdUAAAAVAO1K2cPtGNCt/0CnZvPhFpTDNAHVAAABAGAQ9t8yyHLLj0Q246OVgnVbroT+2xJscI4dnNAKm2r1fyhzBtjzuAgPmjOlCQ2o6+IiGSgD2pJDlTT7q1GlABz8B8+8qrVHezrLmCUoUwCTd1BBf2wNHOe3YPfQAbQKkPWqEcJDJ/Kmp7Hv5MzRd3ThJ8qmRZnAjq9J65UlsH1lN58JV7q/JMK897Sdl+8E4eoMKHBs9pF/uy4FQNlJA8UZt1NxMrqWQN6pfaDUCqujZ9Xxlp8D72qR7XooaFMXSwJYf5Vpd3mm5N4t/rkWknuH89S/khBupTuzYLUzlg8nXM0HBy9FGeYdFh74wTBxJJMHi/z6tSkCFK5FR4V4BVkAAAEAQhgU2f/ecIsnWda8PuJjeCw0Xy5l1j0yx8D3LY1DqSqdwCx6BZbmpNBhdVXzgVC9vQncfCunBFc1szReefs7oX7i/BMiRpEy0/PMX4hhojnXT1t96B/RVAVlvIlCvc5n8ibj3idJ4Fn7ADHUfJ/o52y8IKsttSYEDwi7NZtFPLzQeaS/6WC6gtFHuSgryJIzR7oF2aX+A2FERjv8B4YKzJLaiToAIS+1B2qndgfiLk5QiOPvCaIL/lnHCXLnDgJJ/g42kYREGbr7TBcK3yVhNcUUxptu61abKwATElBdHCiug23E0U/OAT1zkEWGskWEVCtlLhtTaRvzoCkRiEAkEw== peter@onion.home.dataloss.nl"

  lieter:
    state: present
    company: "Pieter Lexis"
    email: pieter+nlnog-ring@plexis.eu
    uid: 6005
    shell: /bin/bash
    groups:
      - ring-admins
      - ring-users
    sshkeys:
      - 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEJUWfeP3PFDrbtZHN40ukmId28mr08mxo2qYaHc3FxLQqZ5mimChxe4KcSZWBgdfheRGIMROTVKcMfnsaorVUA= pieter@aardbei.mobile.plexis.eu'
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBC+hdM7tLIfBlcM0kbTfLB58ufbFs4/5/7wvouBUhPX lieter@aardbei.mobile.plexis.eu'
      - 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDFvrscfrTJEq8X8kEk1SeXwrbN2uKUwcdGH2GSegWZoWMmrA5hhKvt0IlXRxdpYEjs4rT19nE35gSIBfF2EfYA= lieter@ananas.home.plexis.eu'
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINMMEIwWGy839tCt7GJjs2XagCdsXL5TZGnj0kceDccY lieter@ananas.home.plexis.eu'

  grizz:
    state: present
    company: "Matt Griswold"
    email: grizz@20c.com
    uid: 6006
    shell: /bin/bash
    groups:
      - ring-admins
      - ring-users
    sshkeys:
      - 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAB/8EAAf/ZqQI/f+uwUCQkfCpSzjh6fC0rNoS0/wgFAwC4EnnUUj0+NnG8/ib/7TMOZHQOxdUqwwt4dkuoj26lOyAHstuFbxl8mQBFaEWz/pWlay6QJEFfDxM/Kpu5E40Q5b59DbbVGFykPJNox2mB1gQLJFM+YxRbSlhsrvd9xum2vlA== grizz@20c.com'
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvcBYRMAmEMmj7Wlh5MWf5wqoJePWtI+Hrpes/EoV5bsQAY05rGtb1ZZPZG9TDjBqblZeRv+tFMlsEathscuSSJBtR9mAZIicfa/799EjuEXwVGkTsE36VeSqznM7efELJn5l7Nealn6R4WpXUFjmvutVzuqhNIDK/1ZvEY62wRQtlB21flFCulrHje1KxCv7TCfhmRMf7J2A8jXXXiqEVsZ8yF6YNsg7bHpjadgS0vxlNXc8RYqW6LU85b2KxWaybRoWuMY4S/AEQNxrMNUHLUD+qjxbmkTV6cVWlx9yfPb8c3tpZL4x78/Qhae/a1dZcYz3aeO90TJ2cx0xmSLjlQ== grizz@20c.com'
