GROUPS:
  ring-admins:
    gid: 6000
    sudo: true
  ring-users:
    gid: 5000

USERS:
  job:
    state: present
    company: 'Job Snijders'
    email: job@instituut.net
    uid: 6001
    shell: /bin/bash
    groups:
      - ring-admins
      - ring-users
    sshkeys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA4Ejc9Q/RwP5rEY51RdKY3BHpXWYSmePBoppyEjJR5t+/rD7Q2pwbsbrgIm960TpqnOf8ExTje5fCj9yosvqFPgt6K2Tp/9WDkCxMfPj7Fc2rVCFxoTaa2tM/xCgYQpcp+adH/GI0lCsC07FFUHI4+81YLJsxxBm/QExB2gqVZCMH5j+s8q2iWMEQMyXtOdU02/EilUcAcUhPAgoT+U7OG/6bsrBBbVHegQs6uNHfuJtQMh/mmDAeo+qGqBsAIKMtc5H9VGaXNg7jd6wvn8+3EYQ+B1B7NKxEZt/xtWKK4fSdfWiyQY8ZJlGKHrI60dyrW2yKuqcyX3W2hUSQQzp9rQ== job@instituut.net-nlnogring-2011"

  martin:
    state: present
    company: 'Martin Pels'
    email: martin@rodecker.nl
    uid: 6002
    shell: /bin/bash
    groups:
      - ring-admins
      - ring-users
    sshkeys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArZl+3qDiBGF4v3fszgwFti5e4xVoY1fbXsqpAZmbZm1pbSlpJBsHc6ObrxepypoRik5JuiuAoLVFBziEq3m+GgMnUHYbdSBeqHJloa3bIdy8byVGowIYwV4zZyRCwEYuvto7xfUScCSgboBoHs+hU58kyYQxwWRZVCIhEMSIYlwHDCR3juHV1Z50XxgZEJgZeyKxGL4oeeLq9zbQDQxhglygia7nPXUVh+4Z2w6S7oS8prJH5saOg5ixtnBP3isQ5/WOwdAJrcu30s+4P6eWvcJQVtRNZDJyNCctkjCPaN2PVNRvhEu6oeWptwb/pek6LSwmKvUETUHz4W4FKHCKPw== martin@rodecker.nl"

  edwin:
    state: absent

  peter:
    state: present
    company: "Peter van Dijk"
    email: peter+ring@7bits.nl
    uid: 6004
    shell: /bin/bash
    groups:
      - ring-admins
      - ring-users
    sshkeys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDji9oyRQ0EU3F8UkEtfnrn5R2kv/yBOpDUUirfcgMFvyyffT7yagX4hG6DM15LDFYLsG41Jz7AlHyEOVmmh2/4dY3117yCYwAb99UlGOThJFXhYpzeXNmEK4JH/jqV1CreNu30X2gVD1JqTqn3kK/XkgD66AABBIDHZ3bdbikgj/FlNiS7TPJOpoOfotCDL+E/QA25v21zJJXmp69r3laNr4QYvE4VDK/IjiNVY6fb3lhGQJ6rLla2O9E7v0ooIL5tuYnC13pZK0wDVjBo1MSqQNc+QNG849XssXGo3MrGN7syU6CEiMsXlB0bnuJFNykf4AoDZUah6mLYrnNngmZf peter@marconi.local"

  lieter:
    state: present
    company: "Pieter Lexis"
    email: pieter+nlnog-ring@plexis.eu
    uid: 6005
    shell: /bin/bash
    groups:
      - ring-admins
      - ring-users
    sshkeys:
      - 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEJUWfeP3PFDrbtZHN40ukmId28mr08mxo2qYaHc3FxLQqZ5mimChxe4KcSZWBgdfheRGIMROTVKcMfnsaorVUA= pieter@aardbei.mobile.plexis.eu'
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBC+hdM7tLIfBlcM0kbTfLB58ufbFs4/5/7wvouBUhPX lieter@aardbei.mobile.plexis.eu'
      - 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDFvrscfrTJEq8X8kEk1SeXwrbN2uKUwcdGH2GSegWZoWMmrA5hhKvt0IlXRxdpYEjs4rT19nE35gSIBfF2EfYA= lieter@ananas.home.plexis.eu'
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINMMEIwWGy839tCt7GJjs2XagCdsXL5TZGnj0kceDccY lieter@ananas.home.plexis.eu'

  grizz:
    state: present
    company: "Matt Griswold"
    email: grizz@20c.com
    uid: 6006
    shell: /bin/bash
    groups:
      - ring-admins
      - ring-users
    sshkeys:
      - 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAB/8EAAf/ZqQI/f+uwUCQkfCpSzjh6fC0rNoS0/wgFAwC4EnnUUj0+NnG8/ib/7TMOZHQOxdUqwwt4dkuoj26lOyAHstuFbxl8mQBFaEWz/pWlay6QJEFfDxM/Kpu5E40Q5b59DbbVGFykPJNox2mB1gQLJFM+YxRbSlhsrvd9xum2vlA== grizz@20c.com'
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvcBYRMAmEMmj7Wlh5MWf5wqoJePWtI+Hrpes/EoV5bsQAY05rGtb1ZZPZG9TDjBqblZeRv+tFMlsEathscuSSJBtR9mAZIicfa/799EjuEXwVGkTsE36VeSqznM7efELJn5l7Nealn6R4WpXUFjmvutVzuqhNIDK/1ZvEY62wRQtlB21flFCulrHje1KxCv7TCfhmRMf7J2A8jXXXiqEVsZ8yF6YNsg7bHpjadgS0vxlNXc8RYqW6LU85b2KxWaybRoWuMY4S/AEQNxrMNUHLUD+qjxbmkTV6cVWlx9yfPb8c3tpZL4x78/Qhae/a1dZcYz3aeO90TJ2cx0xmSLjlQ== grizz@20c.com'

  sander:
    state: present
    company: "Sander Smeenk"
    email: ssmeenk@freshdot.net
    uid: 6007
    shell: /bin/bash
    groups:
      - ring-admins
      - ring-users
    sshkeys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKeXDbFKwc1yIC/8zqhZATAfy55kNUzXEWpVPyiD224b sanders@fdi-20170319'
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCxSzhxF83AgQaIXvQW17thTrMcmHFMeL0dRfWips7KeEujYSW+ts3ihYoi5ygtj3FT1MD7ZVXP8uJZh08FWkw77qMEv5FL2Wsb7cY4SkXCMAkZ2Xu2Iz9tV3uPDfDzLFANt/KyfTgN2mJNjGczdjUJ8nJYJlGY1zE44ZkibucZKw39zgPMFuOK9rT7efbnGtry0RfujL7plEccLVLAFEIowiKcikk9BSuJgj1EYGggKQyuN/q60lQ6ZWf1Y/6prWe7nTyamCd05ycM3emJWehl5f9TrDMMMqmwaimoHbZEsLmCAHjXuaKM7bbny1C/wPj+tuJn+rDUgrKnjpSPomig3NKV7PQjB2HY3CQoymdgiAE3+W11GemKSMqackckdTzh7/kSvIKtlbYBQ4l7PY4sZZkE+avVL3kzVNHG0Y94bAwn2Xu6c4z0738drd6lBpSGzUnYIMu6vEB+Zl4tSWO4B2a89Fe5tO2OIW+E4hXlawC+ujUBKLfn+M3A7O/x+2rddU8B0srdSkRmRYOm5o9/zxW+T8Tl3dJJ6nxl0RqzjNjPwV8FSQC8C2JmMkZlzdpeRZUNN+5cCHN10eOOTBv0/OudOCgkNO/Br04gD4dtlzCrUDVpiYOIBmSVyXlVdS9dNMzxVmpV4q8a4aGsKue4VceK0FxdwYmahY8IiWdHQ== sanders@haze'
      
