- block:
  - name: "Load user class variables"
    include_vars: "{{ class }}.yml"

  - name: "Add groups for class {{ class }}"
    group: name={{ item }} state={{ GROUPS[item] }}
    with_items: "{{ GROUPS|list }}"

  - include: user_tasks.yml ENTRIES={{ USERS }}
  when: class != "local" 

- block:
  - name: "Add local groups"
    group: name={{ item }} state={{ LOCAL_GROUPS[item] }}
    with_items: "{{ LOCAL_GROUPS|default([])|list }}"

  - name: "Add local users"
    include: user_tasks.yml ENTRIES={{ LOCAL_USERS }}
    when: LOCAL_USERS is defined
  when: class == "local"

