- name: "Load user class variables"
  include_vars: "{{ class }}.yml"
  when: class != "local" 

- name: "Import local groups var"
  set_fact:
    GROUPS: "{{ LOCAL_GROUPS|default(None) }}"
  when: class == "local"

- name: "Import local users var"
  set_fact:
    USERS: "{{ LOCAL_USERS|default(None) }}"
  when: class == "local"

- name: "Add groups"
  group: name={{ item }} state={{ GROUPS[item] }}
  with_items: GROUPS|list

- name: "Add users"
  user:
    name={{ item }}
    state={{ USERS[item].state }}
    uid={{ USERS[item].uid }}
    home="/home/{{ item }}"
    comment="{{ USERS[item].company }} - {{ USERS[item].email }}"
    shell={{ USERS[item].shell|default(user_shell) }}
    groups={{ USERS[item].groups|join( "," ) }}
    append=yes
  with_items: USERS|list

- name: "Add .ssh directories"
  file:
    path="/home/{{ item }}/.ssh"
    state=directory
    owner={{ item }}
    group={{ item }} 
    mode=700
  with_items: USERS|list
  when: USERS[item].state == "present"

- name: "Add hardcoded ssh keys"
  copy:
    dest=/home/{{ item }}/.ssh/authorized_keys
    content="# Generated by Ansible\n{{ USERS[item].sshkeys|join('\n') }}"
    owner={{ item }}
    group={{ item }} 
    mode=700
  with_items: USERS|list
  when: USERS[item].sshkeys is defined and USERS[item].state == "present"

- name: "Find local sshkey files to provision"
  local_action: stat path=roles/users/files/keys/{{ item }}/{{ item }}.sshkeys
  register: keyfiles
  with_items: USERS|list
  when: USERS[item].sshkeys is not defined and USERS[item].state == "present"

- name: "Find per org local sshkey files to provision"
  local_action: stat path=roles/users/files/keys/{{ item }}/{{ item }}-only.sshkeys
  register: keyfiles2
  with_items: USERS|list
  when: USERS[item].sshkeys is not defined and USERS[item].state == "present"

- name: "Add ssh keys from files"
  copy:
    src=keys/{{ item.item }}/{{ item.item }}.sshkeys
    dest=/home/{{ item.item }}/.ssh/authorized_keys
    owner={{ item.item }}
    group={{ item.item }}
    mode=700
  with_items: keyfiles.results
  when: keyfiles.results is defined and item.stat.exists == True

- name: "Add local org ssh keys from files"
  assemble: src=roles/users/files/keys/{{ item.item }} dest=/home/{{ item.item }}/.ssh/authorized_keys
  when: inventory_hostname|match("^{{ item }}\d\d\..*") and keyfiles2.results is defined and item.stat.exists == True
  with_items: keyfiles2.results

- name: "Remove home directories of deleted users"
  file:
    path="/home/{{ item }}"
    state=absent
    recurse=yes
  with_items: USERS|list
  when: USERS[item].state == "absent"

- name: "Clean up old sshkeys on auth host"
  file:
    path=/opt/keys/{{ item }}
    state=absent
    recurse=yes
  with_items: USERS|list
  when: inventory_hostname == "auth.infra.ring.nlnog.net" and USERS[item].state == "absent"

