- name: "Install locales"
  apt: name={{ item }} state=latest
  with_items:
    - locales
    - language-pack-en

- name: "Add default locale"
  copy:
    src=default_locale
    dest=/etc/default_locale
    owner=root
    group=root
    mode=0644
  notify: update-locale

- name: "Add supported locales"
  copy:
    src=supported
    dest=/var/lib/locales/supported.d/local
    owner=root
    group=root
    mode=0644
  notify: update-locale

