---
- name: Apt-pin ansible
  template:
    src: ansible.pref.j2
    dest: /etc/apt/preferences.d/ansible.pref

- name: Ensure Ansible is installed
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - "ansible={{ ansible_pin_version }}"

- name: Ensure Ansible cronjob exists
  template:
    src: cron.d/ansible.j2
    dest: /etc/cron.d/ansible.j2

- name: Remove any old crontab entries
  lineinfile:
    dest: /var/spool/crontabs/root
    regexp: 'ansible(-|_)pull'
    state: absent
