---

#### Ansible from pkgs

- name: "Apt-pin ansible"
  template:
    src: ansible.pref.j2
    dest: /etc/apt/preferences.d/ansible.pref
  when: ansible_distribution_release == "precise"

- name: "Delete apt-pin for ansible"
  file: path=/etc/apt/preferences.d/ansible.pref state=absent
  when: ansible_distribution_release != "precise"

- name: "Ensure Ansible prequisites are installed"
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - python-requests
  when: ansible_distribution_release != "precise"

- name: "Ensure Ansible is installed (xenial)"
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - "ansible={{ ansible_pin_version_xenial }}"
  when: ansible_distribution_release == "xenial"

- name: "Ensure Ansible is installed (bionic)"
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - "ansible={{ ansible_pin_version_bionic }}"
  when: ansible_distribution_release == "bionic"

- name: "Create callback plugin dir"
  file: path={{ item }} state=directory
  with_items:
    - /usr/share/ansible/plugins
    - /usr/share/ansible/plugins/callback

- name: "Install callback module"
  template: src=ring_callback.py.j2 dest=/usr/share/ansible/plugins/callback/ring.py

- name: "Install mitogen"
  git:
    repo: 'https://github.com/dw/mitogen.git'
    dest: /opt/mitogen
    update: "{{ mitogen_update }}"
  when: ansible_distribution_release != "precise"

- name: "Check for mitogen ansible plugin installation"
  stat:
    path: /opt/mitogen/ansible_mitogen/plugins/strategy/mitogen.py
  register: mitogen

- name: "Update ansible.cfg (mitogen)"
  copy:
    src=ansible.cfg
    dest=/etc/ansible/ansible.cfg
    owner=root
    group=root
    mode=0644
  when: mitogen.stat.exists == True

#### END Ansible from pkgs

#### Ansible in a venv

- name: Install Ansible build-deps
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - 'libffi-dev'
    - 'python-virtualenv'
  when: ansible_distribution_release == "precise"

- name: "Ensure Ansible is installed"
  pip:
    name: "ansible"
    version: "{{ ansible_pip_version }}"
    state: present
    virtualenv: "{{ ansible_venv_dir }}"
    virtualenv_python: python2.7
  when: ansible_distribution_release == "precise"

- name: Install Ansible deps
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ ansible_venv_dir }}"
    virtualenv_python: python2.7
  with_items:
    - 'requests'
  when: ansible_distribution_release == "precise"

- name: "Create callback plugin dir"
  file: path={{ item }} state=directory
  with_items:
    - "{{ ansible_venv_dir }}/lib/python2.7/site-packages/ansible/plugins"
    - "{{ ansible_venv_dir }}/lib/python2.7/site-packages/ansible/plugins/callback"
  when: ansible_distribution_release == "precise"

- name: "Install callback module"
  template:
    src: ring_callback.py.j2
    dest: "{{ ansible_venv_dir }}/lib/python2.7/site-packages/ansible/plugins/callback/ring.py"
  when: ansible_distribution_release == "precise"

- name: "Ensure Ansible cronjob exists (venv)"
  template:
    src: cron.d/ansible_virtualenv.j2
    dest: /etc/cron.d/ansible
  when: ansible_distribution_release == "precise"

#### END Ansible in a venv

- name: "Create /var/log/ansible if needed"
  file:
    path: /var/log/ansible
    state: directory
    owner: root
    group: adm
    mode: 0750

- name: "Create /usr/local/sbin if needed"
  file:
    path: /usr/local/sbin
    state: directory
    mode: 0755

- name: "Ensure run-ansible script exists"
  template:
    src: run-ansible.j2
    dest: /usr/local/sbin/run-ansible
    owner: root
    group: root
    mode: 0755
  when: ansible_distribution_release != "precise"

- name: "Ensure ansible-cron script exists"
  template:
    src: ansible-cron.j2
    dest: /usr/local/sbin/ansible-cron
    owner: root
    group: root
    mode: 0755
  when: ansible_distribution_release != "precise"

- name: "Install ansible-reaper"
  copy:
    src=ansible-reaper
    dest=/usr/local/sbin/ansible-reaper
    owner=root
    group=root
    mode=0755
  when: ansible_distribution_release != "precise"

- name: "Ensure Ansible cronjob exists"
  template:
    src: cron.d/ansible.j2
    dest: /etc/cron.d/ansible
  when: ansible_distribution_release != "precise"

- name: "Remove any old ansible crontab entries"
  lineinfile:
    dest: /var/spool/cron/crontabs/root
    regexp: 'ansible(-|_)pull'
    state: absent

- name: "Remove any old salt crontab entries"
  lineinfile:
    dest: /var/spool/cron/crontabs/root
    regexp: 'salt-call'
    state: absent

- name: "Remove old Puppet crontab entries"
  lineinfile:
    dest: /var/spool/cron/crontabs/root
    regexp: "puppetagent|puppetd|zombiekiller|puppet_zombiecleanup|ring-puppet-repo-sync|pull_from_repo"
    state: absent
  when: remove_puppet is defined and remove_puppet

- name: "Remove puppet"
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - puppet
    - puppet-common
    - libaugeas-ruby1.8
    - libaugeas0
    - augeas-lenses
    - libruby
    - libshadow-ruby1.8
    - facter
  when: remove_puppet is defined and remove_puppet

- name: "Remove puppet 'helper' files"
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/puppet_zombiecleanup
    - /usr/local/bin/ring-convert-ssh-keys
    - /usr/local/bin/ring-puppet-repo-sync
    - /var/lib/puppet

- include: master.yml
  when: ansible_master|default(None) == true

