#- name: "Add the ansible ppa key"
#  apt_key: keyserver=keyserver.ubuntu.com id=6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367

#- name: "Add the ansible ppa"
#  apt_repository: repo='deb http://ppa.launchpad.net/ansible/ansible/ubuntu precise main' state=present

#- name: "Install ansible"
#  apt: pkg=ansible state=latest

- name: "Delete Ansible 1.0 plugin dir"
  file: path=/usr/share/ansible_plugins state=absent

- name: "Create callback plugin dir"
  file: path={{ item }} state=directory
  with_items:
    - /usr/share/ansible/plugins
    - /usr/share/ansible/plugins/callback

- name: "Install callback module"
  template: src=ring_callback.py.j2 dest=/usr/share/ansible/plugins/callback/ring.py

#- name: "Add ansible-pull cronjob"
#  cron: name="ansible-pull" minute="{{ 59|random }}" job="ansible-pull -d /etc/ansible/ring -U https://github.com/NLNOG/ring-ansible.git -i nodes playbook.yml >/dev/null 2>/dev/null"

