- name: "Install fail2ban"
  apt: pkg=fail2ban state=latest

- name: "Install jail.local"
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local
  notify:
    - reload systemd
    - restart fail2ban

- name: reload systemd if needed
  meta: flush_handlers

- name: enable fail2ban service
  service:
    name: fail2ban
    enabled: yes
    state: started

