- name: "Install hugo"
  apt: name=hugo state=latest

- name: "Check out hugo source code repositories"
  git:
    repo: "{{ item.repo }}"
    dest: "/var/www/{{ item.name }}.ring.nlnog.net"
  with_items: "{{ hugo_sites|default([]) }}"
  notify: hugo rebuild 

- name: "Copy toml"
  copy:
    src: /var/www/{{ item.name }}.ring.nlnog.net/config.toml.base
    dest: /var/www/{{ item.name }}.ring.nlnog.net/config.toml
    remote_src: "yes"
  with_items: "{{ hugo_sites|default([]) }}"

- name: "Set base URL"
  lineinfile:
    path: /var/www/{{ item.name }}.ring.nlnog.net/config.toml
    regexp: '^baseURL = '
    insertbefore: BOF
    line: "baseURL = \"https://{{ item.name }}.ring.nlnog.net/\""
  with_items: "{{ hugo_sites|default([]) }}"

- name: "Check out hugo theme repositories"
  git:
    repo: "{{ item.theme_repo }}"
    dest: "/var/www/{{ item.name }}.ring.nlnog.net/themes/{{ item.theme_name }}"
  with_items: "{{ hugo_sites|default([]) }}"
  notify: hugo rebuild 

