- name: "Install library dependencies"
  apt: name={{ item }} state=latest
  with_items:
    - libjson-perl
    - libwww-curl-perl

- name: "Make sure site_ruby directory exists (for ring.rb)"
  file:
    path: /usr/local/lib/site_ruby
    state: directory
    mode: 0755

- name: "Install ring.rb"
  copy:
    src=ring.rb
    dest=/usr/local/lib/site_ruby/ring.rb
    owner=root
    group=root
    mode=0755

- name: "Install software dependencies for rbnacl"
  apt: name={{ item }} state=latest
  with_items:
    - libffi-dev

- name: "Install rbnacl with ed22519 support (for ring.rb)"
  gem: name=rbnacl version=4.0.2 executable=/usr/bin/gem user_install=no

- name: "Install various gems for ring.rb"
  gem: name={{ item }} state=latest executable=/usr/bin/gem user_install=no
  with_items:
    - net-ssh
    - rbnacl-libsodium
    - bcrypt_pbkdf
    - ed25519

- name: "Install ring userscripts"
  copy:
    src={{ item }}
    dest=/usr/local/bin/{{ item }}
    owner=root
    group=root
    mode=0755
  with_items:
    - generate-hosts.py
    - ring-all
    - ring-all-serial
    - ring-curl
    - ring-http
    - ring-ping
    - ring-trace
    - ring-uping

