- name: "Create graphite user group"
  group:
    name: graphite
    state: present

- name: "Create sync directory"
  file:
    path: /opt/graphite
    state: directory
    owner: root
    group: graphite
    mode: 0750

- name: "Install user sync script"
  copy:
    src=auth-copy-graphite-credentials
    dest=/usr/local/bin/auth-copy-graphite-credentials
    owner=root
    group=root
    mode=0755

- name: "Add cronjob for auth_sync_graphite_credentials"
  template:
    src: "cron.d/auth_sync_graphite_credentials.j2"
    dest: /etc/cron.d/auth-copy-graphite-credentials

