- name: "Add certbot repository"
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/certbot/certbot/ubuntu xenial main'
    state: present
    filename: 'certbot_repo'
  register: certbot_repo

- name: "Add certbot repository key"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7BF576066ADA65728FC7E70A8C47BE8E75BCA694
  register: certbot_repokey

- name: "Run apt-get update"
  apt:
    update_cache: yes
  when: certbot_repo.changed or certbot_repokey.changed 

- name: "Install certbot"
  apt: name={{ item }} state=latest
  with_items:
    - python-certbot-apache

- name: "Check for existing certificates"
  stat: path=/etc/letsencrypt/live/{{ item }}.ring.nlnog.net/cert.pem
  register: certs_installed
  with_items: "{{ letsencrypt_certs|default([]) }}"

- name: "Generate certificates"
  command: echo /usr/bin/certbot run -a webroot -i apache -w /var/www/html -n -d {{ item.item }}.ring.nlnog.net --agree-tos -m ring-admins@nlnog.net
  with_items: "{{ certs_installed.results }}"
  when: certs_installed.results is defined and item.stat is defined and item.stat.exists == False
